# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\new_notes_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BasicReviewWidget(object):
    def setupUi(self, BasicReviewWidget):
        BasicReviewWidget.setObjectName("BasicReviewWidget")
        BasicReviewWidget.resize(450, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BasicReviewWidget.sizePolicy().hasHeightForWidth())
        BasicReviewWidget.setSizePolicy(sizePolicy)
        BasicReviewWidget.setMinimumSize(QtCore.QSize(450, 400))
        BasicReviewWidget.setMaximumSize(QtCore.QSize(450, 400))
        BasicReviewWidget.setStyleSheet("background-color:black; color: white;")
        self.pushButton = QtWidgets.QPushButton(BasicReviewWidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 320, 75, 23))
        self.pushButton.setStyleSheet("background-color:rgb(8, 40, 92);\n"
"border: 1px solid  rgb(170, 255, 255);\n"
"border-radius: 3px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(BasicReviewWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 320, 75, 23))
        self.pushButton_2.setStyleSheet("background-color:rgb(8, 40, 92);\n"
"border: 1px solid  rgb(170, 255, 255);\n"
"border-radius: 3px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(BasicReviewWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 320, 75, 23))
        self.pushButton_3.setStyleSheet("background-color:rgb(8, 40, 92);\n"
"border: 1px solid  rgb(170, 255, 255);\n"
"border-radius: 3px;")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(BasicReviewWidget)
        QtCore.QMetaObject.connectSlotsByName(BasicReviewWidget)

    def retranslateUi(self, BasicReviewWidget):
        _translate = QtCore.QCoreApplication.translate
        BasicReviewWidget.setWindowTitle(_translate("BasicReviewWidget", "Review"))
        self.pushButton.setText(_translate("BasicReviewWidget", "PushButton"))
        self.pushButton_2.setText(_translate("BasicReviewWidget", "PushButton"))
        self.pushButton_3.setText(_translate("BasicReviewWidget", "PushButton"))
